version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - './backend:/app'
    #   - '/app/node_modules'
    command: npm run start:dev

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - '8080:8080'
    volumes:
      - './frontend/src:/app/src'
      - './frontend/public:/app/public'
      - './frontend/vite.config.ts:/app/vite.config.ts'
    command: npm run dev

  db:
    container_name: database
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - 'v_database:/var/lib/postgresql/data'
    ports:
      - "5432:5432"

volumes:
  v_database: